### ISSUE TITLE
Question about bucket::insert

### ISSUE THREAD

**Issue by shiniaas** [baotonglu/dash#1]
I think the fingerprints should be persisted as your paper says, but I can't find the corresponding code in ex_finger.h(line 369).

**Comment by baotonglu** [comment]
> I think the fingerprints should be persisted as your paper says, but I can't find the corresponding code in ex_finger.h(line 369).

Hi, 

Actually we do some optimization for our implementation for insert performance. The implementation is a little different from the algorithm described in the paper because the current clwb could invalidate the CPU cache. If the fingerprint is flushed before releasing the lock,  the lock release operation will incur high latency because it needs to bring the invalidated fingerprint cacheline from PM to CPU cache. 

Thus our policy is to persist the fingerprints after releasing the lock of that bucket. However, this could incur the issue of "use-before-flush/persist". So current policy to guarantee the correctness is that: release one of the locks (target bucket's or probe bucket's) and then do the fingerprint persist, at last release the remaining lock. The reader (search operation) could proceed only if both locks (target bucket and probe bucket) are released. In other words, this is trading a bit of concurrency for correctness. You could check the Table<T>::Insert function to see that we enforce the persistence of fingerprints after releasing one of the locks. 

Feel free to contact us if you have further questions. Thank you. 

Baotong

**Comment by shiniaas** [comment]
Thanks!
Following your reply, I find what you mean in ex_finger.h(line 879), but there only exists the persistence of bitmap(no fingerprint/finger_array).
Besides, you say  the current clwb could invalidate the CPU cache, confusing me alot(as far as I know, clwb won't invalidate the cacheline).

**Comment by baotonglu** [comment]
> Thanks!
> Following your reply, I find what you mean in ex_finger.h(line 879), but there only exists the persistence of bitmap(no fingerprint/finger_array).
> Besides, you say the current clwb could invalidate the CPU cache, confusing me alot(as far as I know, clwb won't invalidate the cacheline).

The bitmap and fingerprints are in the same cacheline. Therefore flushing the bitmap will also flush the fingerprints. 

Although Intel Xeon Gold 6252 CPU (used in our experiments) supports clwb, our test shows that current clwb actually invalidate the cacheline. Please refer to this blog [1]. 

[1] [clwb](https://blog.haoxp.xyz/posts/is-clwb-implemented/)

**Comment by shiniaas** [comment]
Thanks!
I forgot it!
I'll close this issue.
